In [1]:
import numpy as np

In [2]:
from numpy import random as rnd

Generates random value for the given parameter

In [9]:
x = rnd.randint(1000)
x

871

Generates an Arrany of random integers between 0 and 1000

In [11]:
y = rnd.randint(100 , size=(5))
y

array([15, 68, 57, 47, 32])

Generates an 2-dimensional Array of size(2,5) consisting of integers between 0 to 100


In [14]:
z= rnd.randint(100 , size=(2,5))
z

array([[45, 79, 42, 34, 13],
       [65, 79, 53, 42, 88]])

Choise moule


In [16]:
a= rnd.choice([3,5,7,9] , size = (3,3))
a

array([[3, 5, 7],
       [7, 5, 3],
       [9, 9, 9]])