In [1]:
import numpy as np

In [2]:
from numpy import random as rnd

Generates random value for the given parameter

In [3]:
x = rnd.randint(1000)
x

909

Generates an Arrany of random integers between 0 and 1000

In [4]:
y = rnd.randint(100 , size=(5))
y

array([10, 64, 67, 43, 33])

Generates an 2-dimensional Array of size(2,5) consisting of integers between 0 to 100


In [5]:
z= rnd.randint(100 , size=(2,5))
z

array([[92, 69,  2, 25, 35],
       [45, 16, 49, 20, 19]])

Choise moule


In [6]:
a= rnd.choice([3,5,7,9] , size = (3,3))
a

array([[9, 7, 9],
       [7, 7, 3],
       [9, 3, 7]])